build: false

environment:
    PYTHON_HOME: "C:\\Python37"

    CONAN_REFERENCE: "npcap-npf/0.93"
    CONAN_USERNAME: "bincrafters"
    CONAN_LOGIN_USERNAME: %BT_USER%
    CONAN_LOGIN_PASSWORD: %BT_KEY%
    CONAN_CHANNEL: "stable"
    VS150COMNTOOLS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2015\\Community\\Common7\\Tools\\"
    CONAN_UPLOAD: "https://bintray.com/%CONAN_USERNAME%/public-conan"
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

platform:
  - x86
  - x64
  
configuration:                
  - Win7 Release (WinPcap Mode)
  - Win7 Release
  
install:
  - set PATH=%PYTHON_HOME%;%PYTHON_HOME%/Scripts/;%PATH%
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python build.py
